- name: CSV File Sample
  hosts: all
  vars:
   csv_bash_path: "/var/lib/itam/baselinecheck"
   csv_temp_path: "/tmp/itam/baselinecheck"
  tasks:
    - name: Init Baseline check
      debug:
        msg: "Hello Baseline Check"

    - name: create directory for csv
      file:
        path: "{{ csv_temp_path }}/{{ awx_job_id }}"
        state: directory

    - name: create csv file for test
      file:
        path: "{{ csv_temp_path }}/{{ awx_job_id }}/{{ host_id }}.csv"
        state: touch

    - name: do baseline check
      script: linux_baselinecheck_v2019_0.1.demo.sh "{{ csv_temp_path }}/{{ awx_job_id }}/{{ host_id }}.csv"

    - name: copy csv file back
      fetch:
        src: "{{ csv_temp_path }}/{{ awx_job_id }}/{{ host_id }}.csv"
        dest: "{{ csv_bash_path }}/{{ awx_job_id }}/"
        fail_on_missing: yes
        flat: yes

    - name: delete template file
      file:
        path: "{{ csv_temp_path }}/{{ awx_job_id }}/{{ host_id }}.csv"
        state: absent


